mybatis:
  mapper-locations: classpath:/resources/mybatis/mapper/*.xml
  type-aliases-package: com.hwz.bsbdj.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bsbdj?serverTimezone=GMT%2B8
    username: root
    password: admin